name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Cypress run
        uses: cypress-io/github-action@v6.3.0
        with:
          install-command: yarn install
          brownser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: cf5310ad-6965-42ac-a295-d7d38547313f
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
